#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/GestionCliniqueKissi
#    username: diagana
#    password: diagana
#    driver-class-name: org.postgresql.Driver
#    jpa:
#      hibernate:
#        ddl-auto: create-drop
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
#      database: postgresql
#      database-plateform: org.hibernate.dialect.PostgreSQLDialect
#
